added loader for the calendar
Academia-750/academia750-frontend-vue pull request #36
Opened 2023-10-11 08:38 UTC by kayiganwa04

## Context

Here we are trying to add loader to the calendar before it loads the lessons

[Add a Loader for the calendar (Like the tables?) ](https://www.notion.so/tianlu/Add-a-Loader-for-the-calendar-Like-the-tables-c8af620947524bdbb6e784c875ce436a?pvs=4)

## Test

- Check both calendars for both student and admin
- and check one on mobile responsive

## Platform

## Proof of Concept
<img width="1680" alt="image" src="https://github.com/Academia-750/academia750-frontend-vue/assets/79788219/8857b552-15e8-46d3-a189-0561d50f58fc">

2023-10-12 03:14 UTC, abelbordonado commented on src/modules/lessons/calendar-lessons-list/index.vue
> +      } finally {
I don think we need try catch here, the service layer shall not throw any error.

2023-10-12 03:14 UTC, abelbordonado commented on src/modules/lessons/calendar-lessons-list/index.vue
> +            :loading="isLoading"
I want the flag to leave inside the component, not outside of it :D

2023-10-12 03:14 UTC, abelbordonado commented on src/modules/lessons/calendar-lessons-list/index.vue
> +              :loading="isLoading"
I want the flag to leave inside the component, not outside of it :D

2023-10-12 03:15 UTC, abelbordonado commented on src/modules/lessons/_common/mobile-calendar-lessons-list.vue
> +      default: false
Shall be in the state of the component.

````
async   onLoad(date) {
      if (
        moment(this.focus).isSame(date, 'month') &&
        moment(this.focus).isSame(date, 'year')
      ) {
        return
      }
      this.loading = true
    await  this.$emit('load', {
        start: moment(date).startOf('month').format('YYYY-MM-DD'),
        end: moment(date).endOf('month').format('YYYY-MM-DD')
      })
      this.loading = false
      this.$emit('focus', date)
    },
    
    ````

2023-10-12 03:18 UTC, abelbordonado commented
Good job, but I was looking for something smaller lol

<img width="1018" alt="image" src="https://github.com/Academia-750/academia750-frontend-vue/assets/37141039/23378928-27c5-49ee-a7c4-dabf0d0519f0">

2023-10-12 03:19 UTC, abelbordonado commented
<img width="418" alt="image" src="https://github.com/Academia-750/academia750-frontend-vue/assets/37141039/e76bf3fa-ab1d-407b-ad6e-48ef67ba612b">

2023-10-12 03:19 UTC, abelbordonado commented on src/modules/lessons/_common/calendar-lessons-list.vue
> +            <p class="pa-1">Preparando tu lessiones...</p>
🇪🇸  Preparando tus clases

2023-10-12 03:19 UTC, abelbordonado commented on src/modules/lessons/_common/mobile-calendar-lessons-list.vue
> +      <p class="pa-1">Preparando tu lessiones...</p>
🇪🇸  Preparando tus clases...

2023-10-12 03:41 UTC, abelbordonado requested changes
Requested changes

2023-10-12 16:41 UTC, kayiganwa04 commented on src/modules/lessons/calendar-lessons-list/index.vue
> +            :loading="isLoading"
@abelbordonado I don't get this how will the loading go inside there how will it know if we have the lessons yet?

2023-10-12 16:42 UTC, kayiganwa04 commented on src/modules/lessons/_common/mobile-calendar-lessons-list.vue
> +      default: false
I tried this but we don't see the loaderand I guess is because after emitting it doesn't wait for the lesson to load it automatically goes to loading false

2023-10-13 02:23 UTC, abelbordonado commented on src/modules/lessons/calendar-lessons-list/index.vue
> +      } finally {
Beacuse you got an if () { return }  in middle, `isSelected` just needed to put the loading = false closer to the API return

2023-10-13 02:24 UTC, abelbordonado commented on src/modules/lessons/calendar-lessons-list/index.vue
> +            :loading="isLoading"
For this we need to pass a callback, but we are using events.

Never mind. We keep as it is.

2023-10-13 02:26 UTC, merged