DBT-915 added workspace filter
Academia-750/academia750-frontend-vue pull request #38
Opened 2023-10-12 02:29 UTC by kayiganwa04

## Context

We are adding workspace auto-complete in student materials and recording

[Add Workspace Filter in Student Materials](https://www.notion.so/tianlu/Add-Workspace-Filter-in-Student-Materials-a848f73c1d9146f79b39dfffbc939de9?pvs=4)

## Test

- Login as a student and go to materials and from there you can now filter by workspace

## Platform

## Proof of Concept
<img width="1202" alt="image" src="https://github.com/Academia-750/academia750-frontend-vue/assets/79788219/b060dfc0-bf48-46e0-85f3-f496d2de493e">

2023-10-12 05:31 UTC, abelbordonado commented on src/services/LessonRepository.js
> +   * @param {string} workspaces[0]
Why there is [0]on this documentation?

2023-10-12 05:37 UTC, abelbordonado commented
Now workspaces appear in the Admin -> Lesson -> Material, but is not filtering. Either fix it either hide it (i think before was hidden)

<img width="1220" alt="image" src="https://github.com/Academia-750/academia750-frontend-vue/assets/37141039/91c6f331-77ba-4009-9f40-ee86c9b1be0f">

2023-10-12 05:43 UTC, abelbordonado commented
<img width="966" alt="image" src="https://github.com/Academia-750/academia750-frontend-vue/assets/37141039/d82782bd-e1fd-464b-9bc5-006cf2390940">

2023-10-12 05:53 UTC, abelbordonado commented
<img width="935" alt="image" src="https://github.com/Academia-750/academia750-frontend-vue/assets/37141039/ef51e017-2830-482f-9ba3-f6f2a5bae1c5">

2023-10-12 05:53 UTC, abelbordonado commented
Solve the conflicts :D

2023-10-12 05:53 UTC, abelbordonado requested changes
Requested changes

2023-10-13 10:05 UTC, kayiganwa04 commented
> Now workspaces appear in the Admin -> Lesson -> Material, but is not filtering. Either fix it either hide it (i think before was hidden)
> 
> <img alt="image" width="1220" src="https://user-images.githubusercontent.com/37141039/274491190-91c6f331-77ba-4009-9f40-ee86c9b1be0f.png">

@abelbordonado  this was not hidden before you can even test on main I saw it haven't touched this one in this PR

2023-10-16 04:23 UTC, merged