Workspace PR
Academia-750/academia750-frontend-vue pull request #6
Opened 2023-07-27 14:38 UTC by kayiganwa04

## Context

## Test

## Platform

## Proof of Concept

2023-07-31 11:40 UTC, abelbordonado commented on src/modules/resources/components/resources/add-workspace-modal.vue
> +    },
I dont think we need loading as a prop. Is shall be internal to the modal no? Loading adding user.

2023-07-31 11:40 UTC, abelbordonado commented on src/modules/resources/components/resources/add-workspace-modal.vue
> +    },
? Not required here right?

2023-07-31 11:41 UTC, abelbordonado commented on src/modules/resources/components/resources/add-workspace-modal.vue
> +    },
Is the item a workspace? Lets call it workspace then

2023-07-31 11:43 UTC, abelbordonado commented on src/modules/resources/components/resources/name-field-input.vue
> +<script>
I think we can use the FieldInput common component (as this component has nothing special itself.


<img width="215" alt="image" src="https://github.com/Academia-750/academia750-frontend-vue/assets/37141039/8f922959-8c9a-4c3d-a620-c7310bd0a27b">

2023-07-31 11:44 UTC, abelbordonado commented on src/modules/workspaces/workspace-list/components/NameFieldInput.vue
> +</template>
Duplicated code, I think you added it in common components.

Anyway use the FieldInput general one for the name

2023-07-31 11:44 UTC, abelbordonado commented on src/modules/workspaces/workspace-list/components/workspace-list.vue
> +      </template>
We dont need to render the circle! this is from groups, can remove this template

2023-07-31 11:45 UTC, abelbordonado commented on src/modules/workspaces/workspace-list/components/workspace-list.vue
> +        showConfirmButton: true,
Esta acción es irreversible</b><br>¿Seguro que deseas eliminar este Workspace? Todos los materiales seran borrados del servidor y los alumnos no podrán acceder a ellos',

2023-07-31 11:46 UTC, abelbordonado commented on src/services/WorkspaceRepository.js
> +    }
No need, workspace can be duplicated.

2023-07-31 11:47 UTC, abelbordonado requested changes
Great Job!
Requested some changes! Remember to remove unwanted things on copy-paste.

2023-07-31 12:26 UTC, kayiganwa04 commented on src/modules/resources/components/resources/name-field-input.vue
> +<script>
This field is not working well because it has some email restriction

2023-07-31 12:32 UTC, abelbordonado commented
<img width="1051" alt="image" src="https://github.com/Academia-750/academia750-frontend-vue/assets/37141039/07660095-8d53-4d2b-b183-3be69769c466">


Create Workspace is calling to EDIT workspace now. So I can not create a new workspace

2023-07-31 12:32 UTC, abelbordonado commented on src/modules/resources/components/resources/add-workspace-modal.vue
> +                {{ item ? 'Edit' : 'Create' }}
Editar
Crear

2023-07-31 12:32 UTC, abelbordonado commented on src/modules/resources/components/resources/add-workspace-modal.vue
> +              <span class="text-h6 font-weight-bold">Create Workspace</span>
Crear

2023-07-31 12:33 UTC, abelbordonado commented on src/modules/workspaces/workspace-list/components/workspace-list.vue
> +          <ResourceButtonAdd text-button="Create Workspace" @click="onCreate" />
Crear

2023-07-31 12:36 UTC, abelbordonado commented
<img width="1387" alt="image" src="https://github.com/Academia-750/academia750-frontend-vue/assets/37141039/e6fe36d6-27bc-4572-9414-51dd61b92bc9">

2023-08-02 11:33 UTC, abelbordonado approved these changes
Amazing! now looks great 👍 

Lets do it 🚀

2023-08-02 11:37 UTC, merged